stages:
  create_data:

    cmd: python src/script_a.py --output data/raw_data.csv

    deps:
      - src/script_a.py

    outs: 
      - data/raw_data.csv

  process_data:

    cmd: python src/script_b.py --input data/raw_data.csv --output data/processed_data.csv

    deps:
      - src/script_b.py
      - data/raw_data.csv

    outs:
      - data/processed_data.csv

  process_data_test:

    cmd: python src/script_b.py 
           --input data/raw_data.csv
           --output data/processed_data_test.csv
           --test

    deps: 
      - src/script_b.py
      - data/raw_data.csv

    outs:
      - data/processed_data_test.csv